# -*- coding: utf-8 -*-
"""Breast  Canser Wisconsin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDrPjGi3ABvEW9PMU3L86ElUNEVXD-kM
"""

#step:1 Importing Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,roc_auc_score

# Step:2  Loading Data
df = pd.read_csv('/content/data.csv')
df.columns

#Drop unwanted columns
df.drop(['Unnamed: 32','id'],axis=1,inplace=True)

#Convert target to numeric
df['diagnosis'] = df['diagnosis'].map({'M':1,'B':0})

X=df.drop(['diagnosis'],axis=1)
y=df['diagnosis']

# Step:3 Train-Test Split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

# Step:4 Feature Scaling
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

X_train[:5]

# Step:5 Train Logestic Regression Model
model=LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

# Step:6 Prediction
y_pred=model.predict(X_test)
print("\nPrediction:",y_pred)
y_prob=model.predict_proba(X_test)[:, 1]
print("\nProbability:",y_prob)

# Step:7 Evalution Metrics
accuracy=accuracy_score(y_test,y_pred)
precision=precision_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)
roc_auc=roc_auc_score(y_test,y_pred)
conf_matrix=confusion_matrix(y_test,y_pred)
print("\nAccuracy:",accuracy)
print("\nPrecision:",precision)
print("\nRecall:",recall)
print("\nROC AUC:",roc_auc)
print("\nConfusion Matrix:\n",conf_matrix)

#Interpretation of coefficient
print("\nIntrpreation of coefficient:\n",model.coef_)

#Visualization
fpr,tpr,thresholds=roc_curve(y_test,y_prob)
roc_auc_value=auc(fpr,tpr)
plt.figure(figsize=(8,6))
plt.plot(fpr,tpr,color='darkorange',lw=2,label=f'ROC curve(AUC={roc_auc_value:.3f})')
plt.plot([0,1],[0,1],color='red',linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC & AUC Curve',fontsize=13)
plt.legend(loc='lower right')
plt.show()

